solutions/MathQuizSolution/MathQuiz/Controllers/AppsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MathQuiz.Controllers
{
    public class AppsController : Controller
    {
	    public ActionResult MathGame()
	    {
		    return View();
	    }

    }
}

solutions/MathQuizSolution/MathQuiz/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MathQuiz.Controllers
{
	public class HomeController : Controller
	{
		public ActionResult Index()
		{
			ViewBag.Message = "Modify this template to jump-start your ASP.NET MVC application.";

			return View();
		}

		public ActionResult About()
		{
			ViewBag.Message = "Your app description page.";

			return View();
		}

		public ActionResult Contact()
		{
			ViewBag.Message = "Your contact page.";

			return View();
		}
	}
}

solutions/MathQuizSolution/MathQuiz/Controllers/JasmineController.cs
using System;
using System.Web.Mvc;

namespace MathQuiz.Controllers
{
	public class JasmineController : Controller
	{
		public ViewResult Run(string specName)
		{
			return View(specName);
		}
	}
}

solutions/MathQuizSolution/MathQuiz/Views/Apps/MathGame.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>MathGame</title>
</head>
<body>
	<div id="math-game">
		<div id="countdown"></div>
		<div id="status"></div>
		<span id="question"></span>
		<input type="text" id="answer" />
		<input type="button" value="Answer" id="give-answer" />
	</div>
	<script src="~/Scripts/jquery-2.1.1.js"></script>
	<script src="~/src/Hypertheory/domain/games/mathGame.js"></script>
	<script src="~/src/mathGamePlugin.js"></script>
	<script>
	
		$($('#math-game').mathGame);
	</script>

</body>
</html>

solutions/MathQuizSolution/MathQuiz/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}
<h2>The Following Examples Can Be Viewed:</h2>
<ol>
	<li>Apps</li>
	<ul class="list-unstyled">
		<li>@Html.ActionLink("Math Game Prototype (playable!)", "MathGame", "Apps")</li>
	</ul>
	<li>Specs</li>
	<ul class="list-unstyled">
		<li>@Html.ActionLink("Math Game Plugin Spec", "Run", "Jasmine", new { SpecName = "MathGamePluginSpecRunner" }, null)</li>
		<li>@Html.ActionLink("Math Game Domain Spec", "Run", "Jasmine", new {SpecName="MathGameDomainRunner"}, null)</li>
	</ul>
</ol>

solutions/MathQuizSolution/MathQuiz/Views/Jasmine/MathGameDomainRunner.cshtml
@{
  Layout = null;
}
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
  "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
  <title>Jasmine Spec Runner</title>

  <link rel="shortcut icon" type="image/png" href="/Content/jasmine/jasmine_favicon.png">
  <link rel="stylesheet" type="text/css" href="/Content/jasmine/jasmine.css">
  <script type="text/javascript" src="/Scripts/jasmine/jasmine.js"></script>
  <script type="text/javascript" src="/Scripts/jasmine/jasmine-html.js"></script>
  <script type="text/javascript" src="/Scripts/jasmine/boot.js"></script>
	
	@*sut*@

	<script src="~/src/Hypertheory/domain/games/mathGame.js"></script>
	
	@*specs*@

	<script src="~/specs/mathGameDomain_spec.js"></script>

</head>

<body>
</body>
</html>

solutions/MathQuizSolution/MathQuiz/Views/Jasmine/MathGamePluginSpecRunner.cshtml
@{
  Layout = null;
}
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
  "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
  <title>Jasmine Spec Runner</title>

  <link rel="shortcut icon" type="image/png" href="/Content/jasmine/jasmine_favicon.png">
  <link rel="stylesheet" type="text/css" href="/Content/jasmine/jasmine.css">
  <script type="text/javascript" src="/Scripts/jasmine/jasmine.js"></script>
  <script type="text/javascript" src="/Scripts/jasmine/jasmine-html.js"></script>
  <script type="text/javascript" src="/Scripts/jasmine/boot.js"></script>

	<!-- Support -->
	<script src="~/Scripts/jquery-2.1.1.js"></script>
	<script src="~/specs/TestHelpers.js"></script>
	@*<script src="~/src/Hypertheory/domain/games/mathGame.js"></script>*@
	<!-- SUT -->
	<script src="~/src/mathGamePlugin.js"></script>
	<!-- spec -->
	<script src="~/specs/mathGamePlugin_spec.js"></script>
</head>

	<body>
		<div id="math-game">
			<div id="countdown"></div>
			<div id="status"></div>
			<span id="question"></span>
			<input type="text" id="answer" />
			<input type="button" value="Answer" id="give-answer" />
		</div>
	</body>
</html>

solutions/MathQuizSolution/MathQuiz/Views/Jasmine/SpecRunner.cshtml
@{
  Layout = null;
}
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
  "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
  <title>Jasmine Spec Runner</title>

  <link rel="shortcut icon" type="image/png" href="/Content/jasmine/jasmine_favicon.png">
  <link rel="stylesheet" type="text/css" href="/Content/jasmine/jasmine.css">
  <script type="text/javascript" src="/Scripts/jasmine/jasmine.js"></script>
  <script type="text/javascript" src="/Scripts/jasmine/jasmine-html.js"></script>
  <script type="text/javascript" src="/Scripts/jasmine/boot.js"></script>

  <!-- include source files here... -->
  <script type="text/javascript" src="/Scripts/jasmine-samples/SpecHelper.js"></script>
  <script type="text/javascript" src="/Scripts/jasmine-samples/PlayerSpec.js"></script>

  <!-- include spec files here... -->
  <script type="text/javascript" src="/Scripts/jasmine-samples/Player.js"></script>
  <script type="text/javascript" src="/Scripts/jasmine-samples/Song.js"></script>
</head>

<body>
</body>
</html>

solutions/MathQuizSolution/MathQuiz/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>@ViewBag.Title - My ASP.NET MVC Application</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/bootstrap")
        @Scripts.Render("~/bundles/modernizr")
    </head>
	<body>
		<div class="container">
			<header class="page-header">
				<h1>HTML5 Apps With JavaScript<small> Class Projects</small></h1>
			</header>
			<div class="row">
				@RenderBody()
			</div>
		</div>
       
		
    

		@RenderSection("scripts", required: false)
	</body>
</html>